version: '3.8'
services:
  postgres:
    image: postgres:16.1
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
